# Dockerfile for ORE web application

FROM ubuntu:bionic

ENV ORE_MODE development

RUN apt-get update \
    && apt-get install -y python-dev python-pip scons npm git netcat \
    && rm -rf /var/lib/apt/lists/*

RUN pip install PyXB==1.2.6 defusedxml==0.7.1 psycopg2-binary==2.8.6 django==1.8.18 python-social-auth==0.2.21 python-openid==2.2.5 python-oauth2==1.1.1 django-require==1.0.11 django-robots==3.1.0 django-configurations==2.0 requests_oauthlib==1.1.0 uwsgi==2.0.18

RUN pip install git+https://github.com/django-tastypie/django-tastypie.git@256ebe1de9a78dfb5d4d6e938b813cf4c5c4ac1b

RUN npm install -g less@3.10.0 mocha-phantomjs@4.1.0

COPY frontend/docker/startup.sh /startup.sh

ENV PYTHONUNBUFFERED 1
EXPOSE 8000
CMD ["bash", "/startup.sh"]
