version: '3'

services:
  ore-db-dev:
    image: postgres:9
    container_name: ore-db-dev
    environment:
      POSTGRES_PASSWORD: ore
      POSTGRES_USER: ore
      POSTGRES_DB: ore
    volumes:
      - postgres-volume:/var/lib/postgresql/data  
  ore-front-dev:
    image: troeger/ore-front:0.8.4
    container_name: ore-front-dev
    build: 
      context: .
      dockerfile: ./frontend/docker/Dockerfile.development
    environment:
      ORE_BACKEND_DAEMON: http://ore-back-dev:8000
      ORE_SERVER_URL: http://localhost
      ORE_SERVER: localhost # this adds an entry to allowed hosts
      ORE_DB_NAME: ore 
      ORE_DB_USER: ore 
      ORE_DB_PASSWORD: ore 
      ORE_DB_HOST: ore-db-dev
      ORE_MODE: development
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - ore-db-dev
      - ore-back-dev
    volumes:
      - ./frontend:/ore-front
      - ./common:/ore-common 
  ore-back-dev:
    image: troeger/ore-back:0.8.4
    container_name: ore-back-dev
    build: 
      context: .
      dockerfile: ./backends/docker/Dockerfile.development
    tty: true
    volumes:
      - ./backends:/ore-back 
      - ./common:/ore-common 

volumes:
  postgres-volume:
