version: '3'

services:
  ore-db:
    image: postgres:9
    container_name: ore-db
    environment:
      POSTGRES_PASSWORD: ore
      POSTGRES_USER: ore
      POSTGRES_DB: ore
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  ore-front:
    image: ghcr.io/fidoriel/fuzzed:fe-docker-build-ci
    container_name: ore-front
    build: 
      context: .
      dockerfile: ./frontend/docker/Dockerfile.production
    environment:
      ORE_BACKEND_DAEMON: http://ore-back:8000
      ORE_SERVER_URL: http://localhost
      ORE_SERVER: localhost # this adds a host to allowed hosts
      ORE_DB_NAME: ore 
      ORE_DB_USER: ore 
      ORE_DB_PASSWORD: ore 
      ORE_DB_HOST: ore-db
    ports:
      - 8000:8000
    depends_on:
      - ore-db
      - ore-back

  ore-back:
    image: ghcr.io/fidoriel/fuzzed:fe-docker-build-ci
    container_name: ore-back
    build: 
      context: .
      dockerfile: ./backends/docker/Dockerfile.production

volumes:
  postgres-volume:
